name: Java CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'
      - name: Build with Maven  
        run: mvn --batch-mode --update-snapshots package
      - name: Test with Maven
        run: mvn test